server:
  port: 8002
spring:
  application:
    name: authentication-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: arc
    password: arc

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

