server:
  port: 8001

authentication-service:
  url: http://localhost:8002
review-service:
  url: http://localhost:8001
property-service:
  url: http://localhost:8000
image-processing-service:
  url: http://localhost:8003
config-server:
  url: http://localhost:8004

spring:
  application:
    name: review-service

  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: arc
    password: arc

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Config server
  config:
    import:
      - optional:configserver:http://localhost:8004


# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Zipkin
zipkin:
  base-url: http://localhost:9411
  enabled: true

management:
  tracing:
    sampling:
      probability: 1.0



