server:
  port: 8003

spring:
  application:
    name: property-service

  datasource:
    url: jdbc:postgresql://localhost:5432/image
    username: arc
    password: arc

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB
