server:
  port: 8003

authentication-service:
  url: http://localhost:8002
review-service:
  url: http://localhost:8001
property-service:
  url: http://localhost:8000
image-processing-service:
  url: http://localhost:8003

spring:
  application:
    name: image-processing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/image
    username: arc
    password: arc

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Zipkin
zipkin:
  base-url: http://localhost:9411
  enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
