server:
  port: 8000

spring:
  application:
    name: property-service

  datasource:
    url: jdbc:postgresql://localhost:5432/property
    username: arc
    password: arc

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect


# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
